# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Define the documentation build process
sphinx:
  configuration: docs/source/conf.py

# Define the version of Python
python:
  version: 3.11

# Define how your project should be installed
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11.5"

# Define how to install your project dependencies
python:
  install:
    - requirements: requirements.txt  # Path to the requirements file

# Optionally define the build jobs if you have multiple environments or configurations
# jobs:
#   include:
#     - # Custom build jobs go here